colors:
  body: none
  date: none
  tags: none
  title: none
default_hour: 9
default_minute: 0
editor: 'emacs'
encrypt: true
highlight: true
indent_character: '|'
journals:
  default: /keybase/private/kvlt/journal.txt
  work: /keybase/private/kvlt/work-journal.txt
linewrap: 79
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v2.4.5
